### ISSUE TITLE
Triple atomicity?

### ISSUE THREAD

**Issue by mpetruc** [sberbank-ai/DetIE#6]
First of all, thank you for creating and publishing this system. I did some quick tests: it is very fast and indeed very promising. 
I was wondering if ensuring triple atomicity (or minimality) was one of the goals of project. For example, given the sentence:
ERBB2 is known to activate both the PIK3CA gene and the JAK1 gene.
i am expecting to extract two triples:
ERBB2	activate	the PIK3CA gene 
ERBB2	activate	the JAK1 gene

However, the system extracts only one (compound) triple: ERBB2	activate	the PIK3CA gene and the JAK1 gene

Is this by design? Or are there maybe some configuration settings that i missed?
thanks a lot.

**Comment by alexeyev** [comment]
Hello @mpetruc, thank you for your kind words and your interest.

We did not do anything special to control the atomicity in our model, therefore the output heavily depends on the training dataset (the one from the IMoJIE paper). 

However, after pre-processing the texts with some coordination analysis tool as described in OpenIE6 and DetIE papers (converting the original sentences into smaller ones using the conjunctions hierarchy), DetIE can probably solve the cases like the one in your example.

Best regards, Anton.
